analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - example/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_classes_with_only_static_members: false
    public_member_api_docs: true